/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hprxs3b161;

import javax.swing.JOptionPane;

/**
 *
 * @author lafmah1
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
        public String strRole;
     
    public void mSetRoleRights()
    {
        if(strRole !=null)
        {
            switch(strRole)
            {
                case "ADMIN":
                    mnuLogoff.setEnabled(true);
                    mnuExit.setEnabled(true);
                    mnuRegisterUsers.setEnabled(true);
                    mnuTaskScheduler.setEnabled(true);
                    mnuScheduledTask.setEnabled(false);
                    mnuStaffReport.setEnabled(true);
                    mnuComplaintReport.setEnabled(true);
                    mnuCompliantReg.setEnabled(false);
                    MenuClient.setVisible(false);
                    MenuSecurity.setVisible(false);
                    break;
                case "SECURITY":
                     mnuScheduledTask.setEnabled(true);
                     mnuViewCompliants.setEnabled(true);
                     mnuRegisterUsers.setEnabled(false);
                     mnuTaskScheduler.setEnabled(false);
                     mnuStaffReport.setEnabled(false);
                     mnuComplaintReport.setEnabled(false);
                     mnuCompliantReg.setEnabled(false);
                     MenuAdmin.setVisible(false);
                     MenuClient.setVisible(false);
                     MenuReports.setVisible(false);
                    break;
                case "CLIENT":
                     mnuCompliantReg.setEnabled(true);
                     mnuRegisterUsers.setEnabled(false);
                     mnuTaskScheduler.setEnabled(false);
                     mnuScheduledTask.setEnabled(false);
                     mnuStaffReport.setEnabled(false);
                     mnuComplaintReport.setEnabled(false);
                     MenuAdmin.setVisible(false);
                     MenuSecurity.setVisible(false);
                     MenuReports.setVisible(false);
                    break;
                default:
                    break;
                    
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        dpMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLogoff = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        MenuAdmin = new javax.swing.JMenu();
        mnuRegisterUsers = new javax.swing.JMenuItem();
        mnuTaskScheduler = new javax.swing.JMenuItem();
        MenuClient = new javax.swing.JMenu();
        mnuCompliantReg = new javax.swing.JMenuItem();
        MenuSecurity = new javax.swing.JMenu();
        mnuScheduledTask = new javax.swing.JMenuItem();
        mnuViewCompliants = new javax.swing.JMenuItem();
        MenuReports = new javax.swing.JMenu();
        mnuStaffReport = new javax.swing.JMenuItem();
        mnuComplaintReport = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpMainLayout = new javax.swing.GroupLayout(dpMain);
        dpMain.setLayout(dpMainLayout);
        dpMainLayout.setHorizontalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpMainLayout.setVerticalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        mnuLogoff.setText("Logoff");
        mnuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoffActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogoff);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        MenuAdmin.setText("Administrative ");

        mnuRegisterUsers.setText("Register Users");
        mnuRegisterUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegisterUsersActionPerformed(evt);
            }
        });
        MenuAdmin.add(mnuRegisterUsers);

        mnuTaskScheduler.setText("Task Scheduler");
        mnuTaskScheduler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTaskSchedulerActionPerformed(evt);
            }
        });
        MenuAdmin.add(mnuTaskScheduler);

        jMenuBar1.add(MenuAdmin);

        MenuClient.setText("Client");

        mnuCompliantReg.setText("Compliant Registration");
        mnuCompliantReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCompliantRegActionPerformed(evt);
            }
        });
        MenuClient.add(mnuCompliantReg);

        jMenuBar1.add(MenuClient);

        MenuSecurity.setText("Security");

        mnuScheduledTask.setText("Scheduled Task");
        mnuScheduledTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuScheduledTaskActionPerformed(evt);
            }
        });
        MenuSecurity.add(mnuScheduledTask);

        mnuViewCompliants.setText("Complaints");
        mnuViewCompliants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewCompliantsActionPerformed(evt);
            }
        });
        MenuSecurity.add(mnuViewCompliants);

        jMenuBar1.add(MenuSecurity);

        MenuReports.setText("Reports");

        mnuStaffReport.setText("Staff Report");
        mnuStaffReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStaffReportActionPerformed(evt);
            }
        });
        MenuReports.add(mnuStaffReport);

        mnuComplaintReport.setText("Complaint Report");
        mnuComplaintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComplaintReportActionPerformed(evt);
            }
        });
        MenuReports.add(mnuComplaintReport);

        jMenuBar1.add(MenuReports);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoffActionPerformed
        Login frmL = new Login();
        frmL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuLogoffActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // Exit Program
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit","Exit",JOptionPane.YES_NO_OPTION);

        if(YesOrNo == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuRegisterUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegisterUsersActionPerformed
        RegisterUsers frmRegU = new RegisterUsers();
        dpMain.add(frmRegU);
        frmRegU.setVisible(true);
        frmRegU.setMaximizable(true);
        frmRegU.setIconifiable(true);
        frmRegU.setResizable(true);
        frmRegU.setClosable(true);
    }//GEN-LAST:event_mnuRegisterUsersActionPerformed

    private void mnuTaskSchedulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTaskSchedulerActionPerformed
        TaskScheduler frmTS = new TaskScheduler();
        dpMain.add(frmTS);
        frmTS.setVisible(true);
        frmTS.setMaximizable(true);
        frmTS.setIconifiable(true);
        frmTS.setResizable(true);
        frmTS.setClosable(true);
    }//GEN-LAST:event_mnuTaskSchedulerActionPerformed

    private void mnuCompliantRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCompliantRegActionPerformed
        CompliantReg frmCReg = new   CompliantReg();
        dpMain.add(frmCReg);
        frmCReg.setVisible(true);
        frmCReg.setMaximizable(true);
        frmCReg.setIconifiable(true);
        frmCReg.setResizable(true);
        frmCReg.setClosable(true);
    }//GEN-LAST:event_mnuCompliantRegActionPerformed

    private void mnuStaffReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStaffReportActionPerformed
 
        StaffReport frmSR = new StaffReport();
        dpMain.add(frmSR);
        frmSR.setVisible(true);
        frmSR.setMaximizable(true);
        frmSR.setIconifiable(true);
        frmSR.setResizable(true);
        frmSR.setClosable(true);
    }//GEN-LAST:event_mnuStaffReportActionPerformed

    private void mnuComplaintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComplaintReportActionPerformed
       ComplaintReport frmCR = new ComplaintReport();
        dpMain.add(frmCR);
        frmCR.setVisible(true);
        frmCR.setMaximizable(true);
        frmCR.setIconifiable(true);
        frmCR.setResizable(true);
        frmCR.setClosable(true);
    }//GEN-LAST:event_mnuComplaintReportActionPerformed

    private void mnuScheduledTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuScheduledTaskActionPerformed
        ScheduledTask frmST = new   ScheduledTask();
        dpMain.add(frmST);
        frmST.setVisible(true);
        frmST.setMaximizable(true);
        frmST.setIconifiable(true);
        frmST.setResizable(true);
        frmST.setClosable(true);
    }//GEN-LAST:event_mnuScheduledTaskActionPerformed

    private void mnuViewCompliantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewCompliantsActionPerformed
        ComplaintReport frmCR = new ComplaintReport();
        dpMain.add(frmCR);
        frmCR.setVisible(true);
        frmCR.setMaximizable(true);
        frmCR.setIconifiable(true);
        frmCR.setResizable(true);
        frmCR.setClosable(true);
    }//GEN-LAST:event_mnuViewCompliantsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuClient;
    private javax.swing.JMenu MenuReports;
    private javax.swing.JMenu MenuSecurity;
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuComplaintReport;
    private javax.swing.JMenuItem mnuCompliantReg;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuLogoff;
    private javax.swing.JMenuItem mnuRegisterUsers;
    private javax.swing.JMenuItem mnuScheduledTask;
    private javax.swing.JMenuItem mnuStaffReport;
    private javax.swing.JMenuItem mnuTaskScheduler;
    private javax.swing.JMenuItem mnuViewCompliants;
    // End of variables declaration//GEN-END:variables
}
